### ISSUE TITLE
Build does not work with go 1.10

### ISSUE THREAD

**Issue by Catfriend1** [Catfriend1/syncthing-android#213]
Quote from @jaoh at https://github.com/syncthing/syncthing-android/issues/1047
```
I tried building the commit
7194e25
With go 1.10. The build native target of Gradle fails wit compilation problems

./gradlew --scan buildNative assembleDebug

Configure project :app Signing not ready. Did you specify a signingConfig for the variation Release?

Task syncthing:buildNative FAILED Starting build for arm

Building Syncthing

`# runtime/cgo

In file included from gcc_libinit.c:8:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/pthread.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/time.h:33: In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/time.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/select.h:36:
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:96:18: error: expected ‘;’ at end of declaration list
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/asm/signal.h:85:22: note: expanded from macro ‘sa_handler’
In file included from gcc_libinit.c:8:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/pthread.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/time.h:33:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/time.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/select.h:36:
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:97:12: error: expected ‘)’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/asm/signal.h:86:24: note: expanded from macro ‘sa_sigaction’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:97:10: note: to match this ‘(’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:97:12: error: duplicate member ‘_u’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/asm/signal.h:86:22: note: expanded from macro ‘sa_sigaction’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:96:18: note: previous declaration is here
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin /…/sysroot/usr/include/asm/signal.h:85:20: note: expanded from macro ‘sa_handler’ `

This should be noted in the README.md so that others do not experience this problem.
```

**Comment by Catfriend1** [comment]
Related https://github.com/syncthing/syncthing-android/commit/b4d41901d55a99333d596d4930bbdfc328dbedea
